### ISSUE TITLE
LiveReload does not work

### ISSUE THREAD

**Issue by LukeAskew** [remix-run/grunge-stack#102]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. `npx create-remix@latest`
2. Choose Grunge stack
3. `npm run dev` after the install script finishes
4. Open an incognito browser, change a file, see that that live reloading does not work

### Expected Behavior

The page should reload and reflect the file changes.

### Actual Behavior

The page does not refresh automatically. A manual refresh shows the changes, indicating that the build was successful.

**Comment by machour** [comment]
Any message in the console?
