### ISSUE TITLE
"Lambda handler not found" error due to change in `@architect/architect` v10.6.0

### ISSUE THREAD

**Issue by LukeAskew** [remix-run/grunge-stack#109]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Upgrade `@architect/architect` to `>=10.6`
2. `npm run dev`
3. See error (occasionally)

### Expected Behavior

Arc sandbox should detect the server file and run without issue.

### Actual Behavior

There is a race condition between `remix watch` and `void arc()` that results in arc intermittently not being able to find the server build artifact. This happens pretty consistently on first boot or if the `server/` directory is deleted before the build.

**Comment by LukeAskew** [comment]
Relevant links:
https://github.com/architect/architect/issues/1330
https://github.com/architect/inventory/commit/b890abae17adf741fbe59ee5ae0947ae424bb2e5

Here's my fix in `dev.js`. I'm sure there is a cleaner way, but this might help unblock some folks in the meantime:

```ts
process.env.PORT = process.env.PORT ?? 3000;
process.env.ARC_LOCAL = process.env.ARC_LOCAL ?? 1;
process.env.ARC_TABLES_PORT = process.env.ARC_TABLES_PORT ?? 5555;

const { watchFile, unwatchFile } = require("fs");
const { join } = require("path");
const arc = require("@architect/architect");

const server = join(__dirname, "server/index.js");

// Wait until the server is built
watchFile(server, { interval: 100 }, (curr, prev) => {
  if (!prev.size && curr.size) {
    void arc();
    unwatchFile(server);
  }
});
```

**Comment by jeffstahlin** [comment]
Just ran into this issue as well and tried the fix @LukeAskew suggested but it didn't work. Restarting the server seemed to fix the problem though.
