### ISSUE TITLE
🚀 Fresh Stack Deployment Not Working As Expected

### ISSUE THREAD

**Issue by therealsiege** [remix-run/grunge-stack#115]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

**Steps**
1. Create fresh grunge stack using npx.
2. Connect it to AWS via Github Secrets.
3. Generate Session and Arc App variables.
4. Trigger deployment via dev branch.
5. Access the entry point via the S3 Static Website Hosting URL.

**Reference**
remix.config.js 
`assetsBuildDirectory: "public/build",
  publicPath: "/_static/build/",
  serverBuildTarget: "arc",
  server: "./server.ts",`

### Expected Behavior

🤔 Deployment works, but I'm not seeing the app at the expected URL.

### Actual Behavior

The result is a 404 on every route.

# **404 Not Found**
	- Code: NoSuchKey
	- Message: The specified key does not exist.
	- Key: index.html
	- RequestId: 164GEDTF7M8N85P2
	- HostId: eG7ra0vK8XxFS9FrsYCCttfYBIdIyD0NywlVaKaVmrKmxDyBWXAO7SQW91VIuDUzsBxnn7AVdwo=
 ### **An Error Occurred While Attempting to Retrieve a Custom Error Document**
	- Code: NoSuchKey
	- Message: The specified key does not exist.
	- Key: 404.html

**Comment by mcansh** [comment]
> Access the entry point via the S3 Static Website Hosting URL.

S3 is for the static files (in public directory) only, to access your remix app you'll want to use the api gateway url
