### ISSUE TITLE
Cypress smoke test fails with newly initialized project

### ISSUE THREAD

**Issue by ngtrthinh169TPC** [remix-run/grunge-stack#160]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

```
npx create-remix@latest --template remix-run/grunge-stack
npm run test:e2e:dev
```
Then go to Cypress and run the smoke test.

### Expected Behavior

All the test should pass

### Actual Behavior

Cypress's custom commands cannot be recognized:
- on "should allow you to register and login":
`Type Error: cy.visitAndCheck is not a function`
- on "should allow you to make a note":
`Type Error: cy.login is not a function`

![image](https://github.com/remix-run/grunge-stack/assets/74962522/2dd7a820-ccd9-48d1-b6d1-970a70ee66f4)

![image](https://github.com/remix-run/grunge-stack/assets/74962522/2dbcb1ae-f3bb-46c9-858c-78b4789185c1)

I'm having the same problem with the Indie Stack

**Comment by MichaelDeBoey** [comment]
This seems to be a regression in Cypress with using `Cypress.Command.add`

Fix in #161
