### ISSUE TITLE
401 Unauthorized at localhost. Clerk error integration

### ISSUE THREAD

**Issue by cavaco-jeronimovallelunga** [remix-run/grunge-stack#178]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Installing grunge-stack
2. Integrate Clerk according to official documentation (https://clerk.com/docs/quickstarts/remix)

<img width="1680" alt="Screen Shot 2023-12-13 at 11 53 29" src="https://github.com/remix-run/grunge-stack/assets/152496358/d00a0a76-41fe-4e63-a25d-38865f4e670a">

### Expected Behavior

Redirect to the sign-in screen. 

### Actual Behavior

Infinite loop because of 401 Unauthorized

**Comment by smorimoto** [comment]
Once I comment out ErrorBoundary, the problem seems to go away. In other words, the ErrorBoundary may have a bug.

**Comment by smorimoto** [comment]
So this issue should probably be opened in the Clerk repository.

**Comment by alrightsure** [comment]
Did you end up solving this/opening the issue with Clerk? I tried searching their repo but didn't find it. I am having the same issue as well.

**Comment by scottmuangsrichan** [comment]
Getting the same error. An infinite loop for GET request with a 401 error code. Commented out the ErrorBoundary now just getting a solid 401 on the page without the infinite loop. 

Has anyone found any resources or solution to this issue ?

**Comment by stormynight9** [comment]
I'm having the same issue here. Weird.

**Comment by scottmuangsrichan** [comment]
Hmm what browser for you was causing the issue and what was the browser that happen to work for you?

**Comment by stormynight9** [comment]
@scottmuangsrichan Didn't work on my current instance of Chrome but it does work on Edge.

I just added export ```const ErrorBoundary = ClerkErrorBoundary();``` to my ```root.tsx``` and everything is working fine for now.

**Comment by scottmuangsrichan** [comment]
@stormynight9 okay ya, unfortunately that line of code was the thing causing the error for me. So not sure what the work around is other than rip it out of the project and use a different auth provider.

**Comment by rootsrk** [comment]
I am facing the same issue as well! Is there a workaround for this?

**Comment by scottmuangsrichan** [comment]
@rootsrk haven't found a workaround yet. You can check with the Clerk Discord community and submit a request for help to see if anyone there has found a solution.

**Comment by MichaelDeBoey** [comment]
Closing as this seems to be a Clerk issue instead of a grunge-stack issue
