### ISSUE TITLE
Logout route is not destroying the user session

### ISSUE THREAD

**Issue by McNouvion** [remix-run/grunge-stack#183]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Just setup a new project, create an account and login, then hit '/logout' 
When I get back to the home page I'm still signed in ... 

I did not spend a ton of time trying to figure out the root cause but nothing I did in the `session.server.ts` file seemed to have any effects. I suspect something else is setting/committing the session back in? 

For now I just updated the `logout.tsx` loader which I think is called out as something you should not do in the docs 
(?? Sorry I have only started using remix a few weeks ago).

```
export const loader = async ({ request }: LoaderFunctionArgs) => {
  const session = await getSession(request);

  return redirect("/", {
    headers: {
      "Set-Cookie": await sessionStorage.destroySession(session),
    },
  });
};
```

### Expected Behavior

When I hit the `/logout` route, the session is destroyed and I'm redirected to the homepage where I see a login and a signup button.

### Actual Behavior

I'm redirected to the homepage where I see the "View notes" button.
I also cannot navigate to the login page.

**Comment by mcansh** [comment]
get requests shouldn't be used for mutating data https://remix.run/docs/en/main/utils/sessions#session-gotchas:~:text=It%27s%20important%20that%20you%20logout if you want UI for the `/logout` route there's an example right above where that link points to

**Comment by falecci** [comment]
The `/logout` route code is:

```tsx
import type { ActionFunctionArgs } from "@remix-run/node";
import { redirect } from "@remix-run/node";

import { logout } from "~/session.server";

export const action = async ({ request }: ActionFunctionArgs) =>
  logout(request);

export const loader = async () => redirect("/");
```

This means that if you hit `/logout` in the browser, you will go into the `loader` path, not the `action`. That's why you are being just redirected and not logging out.

If you want to logout via url, you can just update the loader function as the following

```tsx
import type { ActionFunctionArgs, LoaderFunctionArgs } from "@remix-run/node";

import { logout } from "~/session.server";

export const action = async ({ request }: ActionFunctionArgs) =>
  logout(request);

export const loader = async ({ request }: LoaderFunctionArgs) =>
  logout(request);
```

If you want to log out by using the action, you'll need a `Form`.

```tsx
        <Form action="/logout" method="post">
          <button
            type="submit"
          >
            Log out
          </button>
        </Form>
```

**Comment by McNouvion** [comment]
Thank you, that works :)
