### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jarimustonen** [remix-run/grunge-stack#184]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Run the command `npx create-remix@latest --template remix-run/grunge-stack`
2. Answer the default answer to each and every question

### Expected Behavior

A working project.

### Actual Behavior

Here's the default installation:

```
jari@lucille Sources % npx create-remix@latest --template remix-run/grunge-stack


 remix   v2.6.0 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./my-remix-app

      ◼  Template: Using remix-run/grunge-stack...
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         Yes

  init   This template has a remix.init script. Do you want to run it?
         Yes

 ██████  Dependencies installing with npm...

      ▲  Oh no! Failed to install dependencies.
jari@lucille Sources %
```

If we look deeper, it shows the following error:

```
jari@lucille Sources % cd my-remix-app
jari@lucille my-remix-app % npm install
npm ERR! code ERESOLVE
[...]
npm ERR! While resolving: @remix-run/dev@2.6.0
npm ERR! Found: vite@4.5.2
[...]
npm ERR! Conflicting peer dependency: vite@5.0.12
[...]
jari@lucille my-remix-app %
```

**Comment by McNouvion** [comment]
Same issue as https://github.com/remix-run/grunge-stack/issues/180 which @cypherpower opened a PR for (See: https://github.com/remix-run/grunge-stack/pull/181)

The tldr; is that you just need to update 'vite' by running:

```
npm install -S vite@latest
```
