### ISSUE TITLE
Architect Deployment order of Static assets

### ISSUE THREAD

**Issue by joe-l-bright** [remix-run/grunge-stack#27]
Hello!  I did a deep dive into this stack tonight and have found an issue that I would like to get your thoughts on.  It appears when Architect deploys the static assets, it does it in alphabetical order (or maybe random?).  As you can guess, if we upload root first and a User goes to the app, they will get unexpected results since all the assets are not fully published.  I have recreated this very easily by changing a few different files and adding new tailwind css classes so it will regen the .css file.  I don't think this is a technical issue with Remix but I wanted to bring this up and offer to help drive a solution.  Off the top of my head, I think the solution is uploading all of the assets except for the root file, leaving that last.  I did some api doc searches in Architect, but I could not find a config that would allow us to affect the static asset upload process.  

**_Great job on all of the work Remix has done so far!_**

**Comment by martinhrvn** [comment]
I think this issue in architect is related: https://github.com/architect/architect/issues/1312 and I think it may have been fixed in the meantime
