### ISSUE TITLE
Should ARC_APP_SECRET also be mentioned under Deployment in the docs?

### ISSUE THREAD

**Issue by fzembow** [remix-run/grunge-stack#31]
It's my first time using Architect, and I've really enjoyed Remix! Really excited about this combo.

When following the getting started guide, in the **Deployment** section

> ⚠️ Warning: The environment variable "ARC_APP_SECRET" is not set - please set this in production to help mitigate potential session-related attacks!

Looking at the Architect [docs on security](https://arc.codes/docs/en/reference/cli/env#security), it definitely seems important to set.

Perhaps

```
npx arc env --add --env production ARC_APP_SECRET $(openssl rand -hex 32)
```

Should be added to the docs above the other production secret being set? I can make a quick PR if that makes sense.

**Comment by kentcdodds** [comment]
Cc @tbeseda sound good?

**Comment by tbeseda** [comment]
@fzembow @kentcdodds Yep, good call. I think both staging and production should have this set.
