### ISSUE TITLE
dev.js not needed?

### ISSUE THREAD

**Issue by johncantrell97** [remix-run/grunge-stack#36]
Since we are not requiring the mocks in `dev.js` anymore, is this file still needed? 

Couldn't we just start the sandbox using arc sandbox directly?

**Comment by kentcdodds** [comment]
I like the port customization that `dev.js` provides, but yeah, now I think it's safe to remove that file.

**Comment by felixhageloh** [comment]
is there a recommended place to seed your db in this stack (handy since it gets wiped)? I am currently doing it inside dev.js

**Comment by kentcdodds** [comment]
There's not anything recommended by us. Maybe @tbeseda has an idea?

**Comment by tbeseda** [comment]
Hey 👋  yeah there's a new-ish feature in Arc Sandbox to automatically seed data on startup https://arc.codes/docs/en/reference/cli/sandbox#database-seed-data
