### ISSUE TITLE
After deployment, bucket returns 404 and API returns 500

### ISSUE THREAD

**Issue by liampmccabe** [remix-run/grunge-stack#37]
Bucket
![image](https://user-images.githubusercontent.com/3018957/160299178-7030c7a0-9fee-4e9e-a0a8-1f39e06a890f.png)

API
![image](https://user-images.githubusercontent.com/3018957/160299298-6f61683c-d8d9-41c9-9b1c-dd792af6d595.png)

**Comment by liampmccabe** [comment]
Seems like the lambda function the SESSION_SECRET env variable.

```
"errorType": "Error",
"errorMessage": "Invariant failed: SESSION_SECRET must be set"
```

**Comment by kentcdodds** [comment]
<img width="850" alt="image" src="https://user-images.githubusercontent.com/1500684/160480566-5df5d820-9ea2-4184-bdcb-f9c269de5d05.png">

Did you do this step in the README?

**Comment by liampmccabe** [comment]
I did yes, successfully too. 

Though for some reason it wasn't added to the lambda function. 

Just added it manually and it works 🥳

Great work with Remix! Love it!

**Comment by kentcdodds** [comment]
Glad you got it working :)

**Comment by kennethvdberghe** [comment]
Yea, I have the same issue... Seeing arc env variables being added, but not being set in the lambda.

**Comment by eXigentCoder** [comment]
> <img alt="image" width="850" src="https://user-images.githubusercontent.com/1500684/160480566-5df5d820-9ea2-4184-bdcb-f9c269de5d05.png">
> 
> Did you do this step in the README?

I ran these commands locally but I'm a little confused as to how to _"give your CloudFormation a `SESSION_SECRET` variable..."_
Should the `deploy.yml` file be updated to have:
```
SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
ARC_APP_SECRET: ${{ secrets.ARC_APP_SECRET }}
```

Under the relevant staging/production deploy? Or is this something I need to add to the stack somehow on AWS?

**Comment by tbeseda** [comment]
Environment variables created with `arc env --add` are persisted between deployments in the same CloudFormation "stack".

So if you set them from your local machine, and your GitHub Action deploys to that same target, your Action does not need to set them again.

Note that if you change the region or name of your project in `app.arc` you will create a new Stack and will need to set the environment variables again.

**Comment by eXigentCoder** [comment]
Ah, that makes sense, thank you very much!
