### ISSUE TITLE
Bug: Internal Server Error on Lambda

### ISSUE THREAD

**Issue by simonireilly** [remix-run/grunge-stack#44]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

Deploy the template to AWS using the arc deployment

Attempt to sign up

Expect a 500 internal server error

### Expected Behavior

Sign up should succeed

### Actual Behavior

There is an internal server error with no logging at the time bycryptjs attempts to hash the password.

I added a try catch, still no error. So at that point I assumed this is a very low level issue.

Indeed, I added more memory to the aws lambda deployment to 1024 MB from the default 128 MB and hashing did not fail, I was able to log in.

I would suggest that the declaration:

```
memory 1024
```

Is added to the lambda, potentially 512 could fix the issue. I was not able to determine if it was due to CPU or RAM and both scale on memory within lambda

**Comment by mcansh** [comment]
strange, I'm not getting a 500 on https://du9zh091t2.execute-api.us-west-2.amazonaws.com using the default settings

**Comment by machour** [comment]
Closing this issue as no response was provided.
Feel free to re-open it if it's still a problem.

**Comment by anthonywebb** [comment]
I have seen this after adding a VPC to the lambda, when you do that the lambda can no longer talk to the dynamodb server and the page will crash very low level.  Tried adding an endpoint gateway to dynamodb which should allow the lambda in the VPC to talk to the public dynamo but it doesn't work.  More info here https://repost.aws/questions/QUsOBNlERPQZejZsyo3rtxGg/lambda-in-private-subnet-cannot-reach-dynamo-db
