### ISSUE TITLE
Error: Invariant failed: SESSION_SECRET must be set

### ISSUE THREAD

**Issue by MiguelNiblock** [remix-run/grunge-stack#71]
### What version of Remix are you using?

1.5.1

### Steps to Reproduce

npx create-remix
gave it a name
chose "a pre-configured stack ready for prod..."
chose "Grunge" stack
chose "Typescript"
do you want me to run npm install? no
cd into new project directory
yarn
yarn dev
visit localhost:3000
see error

---

  "dependencies": {
    "@architect/architect": "^10.3.3",
    "@architect/functions": "^5.1.0",
    "@remix-run/architect": "^1.5.1",
    "@remix-run/node": "^1.5.1",
    "@remix-run/react": "^1.5.1",
    "@remix-run/server-runtime": "^1.5.1",
    "bcryptjs": "2.4.3",
    "cuid": "^2.1.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "tiny-invariant": "^1.2.0"

### Expected Behavior

run dev should load the initial page

### Actual Behavior

getting this error:
```
Error

Process exited with 1

/home/user/MyProjects/remix-samples-rn/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^
/home/user/MyProjects/remix-samples-rn/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
    ^

Error: Invariant failed: SESSION_SECRET must be set
    at invariant (/home/user/MyProjects/remix-samples-rn/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at Object. (/home/user/MyProjects/remix-samples-rn/app/session.server.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at [eval]:1:336
    at Script.runInThisContext (node:vm:131:12)
```

**Comment by mcansh** [comment]
when you opt out of `npm install` you should see the following which instructs you to run `npx remix init` ![image](https://user-images.githubusercontent.com/11698668/173191363-76d9bc06-12c2-4ea1-b2ff-a10c9e726e94.png)

**Comment by machour** [comment]
@MiguelNiblock did you follow the instruction closely when opting out of installing dependencies?

**Comment by JonathanRys** [comment]
This happened to me after I ran:
```
npx arc env --add --env staging ARC_APP_SECRET $(openssl rand -hex 32)
npx arc env --add --env staging SESSION_SECRET $(openssl rand -hex 32)
npx arc env --add --env production ARC_APP_SECRET $(openssl rand -hex 32)
npx arc env --add --env production SESSION_SECRET $(openssl rand -hex 32)
```

To fix it I ran:
```
npx arc env --add --env testing ARC_APP_SECRET $(openssl rand -hex 32)
npx arc env --add --env testing SESSION_SECRET $(openssl rand -hex 32)
```

**Comment by mcansh** [comment]
@JonathanRys you ran the first set of arc env commands and then `npm run dev` and it failed? then ran the second set and it worked?

mine is working fine without setting the "testing" ones

**Comment by technoY2K** [comment]
> Edit: For the record, I was able to get everything running by setting both the DATABASE_URL env variable (required in this stack for sqlite) and the SESSION_SECRET env variables (to random string). After that, I got remix running!
 
 Wanted to add to this. I did the exact same thing and it worked for me. Just as a note, if you look in the `session.server.ts` file on line 17, you will see that there is an invariant that checks whether a `SESSION_SECRET` is set or not. If you don't have an `.env` with that value set, which `process.env` is doing, the invariant trips and throws the error. This is actually a reason why I prefer these stacks to be just bare bones without any application code.

**Comment by mirsahib** [comment]
I fixed it by duplicating the `.env.example` file and renaming it to `.env` boom

**Comment by LeoBorquez** [comment]
> This happened to me after I ran:
> 
> ```
> npx arc env --add --env staging ARC_APP_SECRET $(openssl rand -hex 32)
> npx arc env --add --env staging SESSION_SECRET $(openssl rand -hex 32)
> npx arc env --add --env production ARC_APP_SECRET $(openssl rand -hex 32)
> npx arc env --add --env production SESSION_SECRET $(openssl rand -hex 32)
> ```
> 
> To fix it I ran:
> 
> ```
> npx arc env --add --env testing ARC_APP_SECRET $(openssl rand -hex 32)
> npx arc env --add --env testing SESSION_SECRET $(openssl rand -hex 32)
> ```

this works for me too , Thank you

**Comment by GaneshSrambikal** [comment]
> I fixed it by duplicating the `.env.example` file and renaming it to `.env` boom

This works as well.
