### ISSUE TITLE
The `cy.cleanupUser` function mentioned in README is missing

### ISSUE THREAD

**Issue by miktap** [remix-run/grunge-stack#82]
### Have you experienced this bug with the latest version of the template?

yep

### Steps to Reproduce

Follow the README and add: 

```ts
afterEach(() => {
  cy.cleanupUser();
});
```

to the Cypress test file (`smoke.cy.ts`). Run Cypress tests.

### Expected Behavior

Tests succeed and test users are deleted from db.

### Actual Behavior

Tests fail with `TypeError: cy.cleanupUser is not a function`

**Comment by machour** [comment]
Looks like this was a leftover from a remove feature, see https://github.com/remix-run/grunge-stack/issues/13 for more details.

You can have a look at the `commands.ts` file in the Indie stack if you want to see what the implementation looked like: 
 https://github.com/remix-run/indie-stack/tree/bd45001a942158f7d7e39b4e65dc2277824d0261/cypress/support
