### ISSUE TITLE
Fresh Grunge-Stack results in many browser console errors

### ISSUE THREAD

**Issue by JasonWeiseUnreal** [remix-run/grunge-stack#86]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. npx create-remix --template remix-run/grunge-stack
2. npx remix init
3. npm run dev

NOTE: This is completely fresh first run, no changes made at all.

### Expected Behavior

No errors in console.

### Actual Behavior

<img width="1804" alt="Screenshot 2022-07-18 093535" src="https://user-images.githubusercontent.com/10267904/179429417-653dafd8-7034-4b94-83a4-2f518e269ac0.png">

**Comment by JasonWeiseUnreal** [comment]
I have depoyed to a production AWS environment as a test and it appears as if these errors only occur on local dev machines.

I am now guessing they can be safely ignored and this issue could be closed but I thought I would just check... 

Is it safe to just ignore these console errors?

**Comment by dr3** [comment]
I have deployed this to production AWS and I still get this error (though of course the react minified versions #418 & #423)

**Comment by dr3** [comment]
This isnt a feature of this stack, it happens on the default one too 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/11341355/185463719-4fa5349b-9d6e-46cd-814d-75ead17ce604.png">

**Comment by dr3** [comment]
Related issue https://github.com/remix-run/remix/issues/2947

**Comment by machour** [comment]
See also this gotcha entry: https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code
Closing this issue as it's not related to this repo.
