### ISSUE TITLE
Try creating new Remix project using grunge stack but the cli freeze after asking me want to run verify build/tests/etc script

### ISSUE THREAD

**Issue by Senbonzakura1234** [remix-run/grunge-stack#94]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

1./ Open PowerShell
2./ Run `npx create-remix@latest`
3./ Select options as the image below
![Step to reproduce](https://user-images.githubusercontent.com/43206347/184348439-cf8ce0ee-c89e-4f43-83a5-33d3f8b05762.png)

### Expected Behavior

The cli should proceed to the next step after I type 'N' and hit enter for `Do you want to run the build/tests/etc to verify things are setup properly?`

### Actual Behavior

The cli freezed

**Comment by mcansh** [comment]
hey @Senbonzakura1234 i've not seen this behavior in my testing, did you by chance hit 'Enter' after typing 'N'?

**Comment by Senbonzakura1234** [comment]
> hey @Senbonzakura1234 i've not seen this behavior in my testing, did you by chance hit 'Enter' after typing 'N'?

Yes i did, i'm pretty sure i did because i see the pointer was under the question line

**Comment by Senbonzakura1234** [comment]
> hey @Senbonzakura1234 i've not seen this behavior in my testing, did you by chance hit 'Enter' after typing 'N'?



> > hey @Senbonzakura1234 i've not seen this behavior in my testing, did you by chance hit 'Enter' after typing 'N'?
> 
> Yes i did, i'm pretty sure i did because i see the pointer was under the question line. It should showing some loading text but it didn't and the whole cli paused at that point, it didnt close or throw any errors

And actually even if i type "y" and press enter, the result still the same, it didnt proceed to run those build/test script that the cli mentioned.

**Comment by mcansh** [comment]
huh weird, ok, in my windows instance i can reproduce this now 🤔 but it does make it through if i hit Enter twice - taking a look

**Comment by Senbonzakura1234** [comment]
> huh weird, ok, in my windows instance i can reproduce this now 🤔 but it does make it through if i hit Enter twice - taking a look

Damm, it's true that hit enter twice work, should i close this issue?

**Comment by Senbonzakura1234** [comment]
> huh weird, ok, in my windows instance i can reproduce this now 🤔 but it does make it through if i hit Enter twice - taking a look

oh heck it's still have bug, take a look at this 
![Screenshot 2022-08-12 185145](https://user-images.githubusercontent.com/43206347/184466354-258ed136-7c02-4092-a1f5-22103da5e9a8.png)

Despite i type "y", when i hit the enter 2nd time, it seems the cli consume it as a No, and ignore my 1st input.
