### ISSUE TITLE
Replace `run-p` with `npm-run-all -p-` because the former doesn't kill all process when pressing CTRL+C in windows

### ISSUE THREAD

**Issue by GiancarlosIO** [remix-run/grunge-stack#95]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

1. run `npx create-remix my-app --template remix-run/grunge-stack`
2. `cd my-app`
3. run `pnpm dev`
4. Try to kill the process pressing CTRL+C

### Expected Behavior

On windows, pressing CTRL+C should kill all the processes of the "dev" npm script.

### Actual Behavior

On windows, pressing CTRL+C DOESN'T kill all the processes of the "dev" npm script. 
It works if I replace the `run-p` with `npm-run-all -p`

**Comment by SirZach** [comment]
I experience this occasionally on a Mac. Switching to `npm-run-all -p` does seem to help

**Comment by mcansh** [comment]
odd, as far i know, they are the same 🤷‍♂️ 

is there an open issue on the `npm-run-all` repo?

**Comment by mcansh** [comment]
in any case, i'd be happy to merge a PR that switches it over :)
